SELECT TO_CHAR (SYSDATE, 'YYYY')||'년 '||
       TO_CHAR (SYSDATE, 'IW')||'주차 '||
       TO_CHAR (SYSDATE, 'MM')||'월 '||
       TO_CHAR (SYSDATE, 'W')||'주차 '||
       TO_CHAR (SYSDATE, 'Q')||'사분기'
FROM DUAL;

SELECT * FROM COUNTRIES;

--! 3 * (LEVEL-1) 만큼 띄어쓰고 출력. (계층구조)
SELECT A.EMPLOYEE_ID, LPAD (' ', 3 * (LEVEL-1)) || A.EMP_NAME, LEVEL,
       B.DEPARTMENT_NAME
  FROM EMPLOYEES A,
       DEPARTMENTS B
 WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
 START WITH A.MANAGER_ID IS NULL
 CONNECT BY PRIOR A.EMPLOYEE_ID = A.MANAGER_ID;

--! 대문자를 지워
SELECT REGEXP_REPLACE(COU, '[A-Z[:space:]]', '') FROM COUNTRIES;


--! DEPARTMENT_ID = 30
SELECT A.EMPLOYEE_ID, LPAD (' ', 3 * (LEVEL-1)) || A.EMP_NAME, LEVEL, A.DEPARTMENT_ID,
       B.DEPARTMENT_NAME
  FROM EMPLOYEES A,
       DEPARTMENTS B
 WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
   AND A.DEPARTMENT_ID = 30
 START WITH A.MANAGER_ID IS NULL
 CONNECT BY PRIOR A.EMPLOYEE_ID = A.MANAGER_ID;
 
 --! 동등 JOIN
 SELECT A.EMPLOYEE_ID, A.EMP_NAME, A.DEPARTMENT_ID, B.DEPARTMENT_NAME
   FROM EMPLOYEES A,
        DEPARTMENTS B
  WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID;
  
--! 세미 JOIN
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
  FROM DEPARTMENTS A
  WHERE EXISTS ( SELECT * 
                   FROM EMPLOYEES B
                  WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
                    AND B.SALARY > 3000 )
ORDER BY A.DEPARTMENT_NAME;    
  
SELECT * FROM DEPARTMENTS;

--! 안티 JOIN
SELECT A.EMPLOYEE_ID, A.EMP_NAME, A.DEPARTMENT_ID, B.DEPARTMENT_NAME
  FROM EMPLOYEES A,
       DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
  AND A.DEPARTMENT_ID NOT IN ( SELECT DEPARTMENT_ID
                               FROM   DEPARTMENTS
                               WHERE  MANAGER_ID IS NULL );

--! MANAGER_ID가 존재하는 인원
SELECT COUNT(*)
  FROM EMPLOYEES A
  WHERE NOT EXISTS( 
                SELECT 1
                FROM DEPARTMENTS C
                WHERE A.DEPARTMENT_ID = C.DEPARTMENT_ID
                AND MANAGER_ID IS NULL);
        
SELECT * FROM EMPLOYEES;

--! 외부 JOIN
SELECT A.DEPARTMENT_ID, A.DEPARTMENT_NAME, B.JOB_ID, B.DEPARTMENT_ID
  FROM DEPARTMENTS A,
       JOB_HISTORY B
  WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID;
  

--! 셀프 JOIN
SELECT A.EMPLOYEE_ID, A.EMP_NAME, B.EMPLOYEE_ID, B.EMP_NAME, A.DEPARTMENT_ID
  FROM EMPLOYEES A,
       EMPLOYEES B
 WHERE A.EMPLOYEE_ID < B.EMPLOYEE_ID
   AND A.DEPARTMENT_ID = B.DEPARTMENT_ID
   AND A.DEPARTMENT_ID = 20;
   
--! 외부 JOIN
SELECT A.DEPARTMENT_ID, A.DEPARTMENT_NAME, B.JOB_ID, B.DEPARTMENT_ID
  FROM DEPARTMENTS A,
       JOB_HISTORY B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID;


SELECT A.DEPARTMENT_ID, A.DEPARTMENT_NAME, B.JOB_ID, B.DEPARTMENT_ID
  FROM DEPARTMENTS A,
       JOB_HISTORY B
 WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID(+);
 
 SELECT A.DEPARTMENT_ID, A.DEPARTMENT_NAME, B.JOB_ID, B.DEPARTMENT_ID
  FROM DEPARTMENTS A,
       JOB_HISTORY B
 WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID(+)
   AND A.DEPARTMENT_ID = B.DEPARTMENT_ID(+);

--! 카타시안 JOIN
SELECT A.EMPLOYEE_ID, A.EMP_NAME, B.DEPARTMENT_ID, B.DEPARTMENT_NAME
  FROM EMPLOYEES A,
       DEPARTMENTS B;

--! ANSI JOIN
SELECT A.EMPLOYEE_ID, A.EMP_NAME, B.DEPARTMENT_ID, B.DEPARTMENT_NAME
  FROM EMPLOYEES A
 INNER JOIN DEPARTMENTS B
    ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID )
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
  AND A.HIRE_DATE >= TO_DATE('2003-03-01', 'YYYY-MM-DD');

--! SELF JOIN
SELECT A.EMPLOYEE_ID, B.EMPLOYEE_ID, A.EMP_NAME, B.EMP_NAME, A.DEPARTMENT_ID
  FROM EMPLOYEES A,
       EMPLOYEES B
 WHERE A.EMPLOYEE_ID   < B.EMPLOYEE_ID
   AND A.DEPARTMENT_ID = B.DEPARTMENT_ID
   AND A.DEPARTMENT_ID = 20;
  
SELECT A.EMPLOYEE_ID,  A.EMP_NAME, B.EMPLOYEE_ID, B.EMP_NAME, A.DEPARTMENT_ID
  FROM EMPLOYEES A,
       EMPLOYEES B
 WHERE A.EMPLOYEE_ID < B.EMPLOYEE_ID   AND A.DEPARTMENT_ID = 20;
 
 SELECT A.EMPLOYEE_ID,  A.EMP_NAME, B.EMPLOYEE_ID, B.EMP_NAME, A.DEPARTMENT_ID
  FROM EMPLOYEES A,
       EMPLOYEES B
 WHERE A.EMPLOYEE_ID < B.EMPLOYEE_ID;
 